README.md

proofreading edits

---

offchain/README.md

Our documentation has gotten a bit out of date. This is a work-in-progress PR that points put some things that have gotten out of date (in particular: building and bundling the project). It also adds missing documentation for native token reserve management commands.
In general, the documentation needs more work. We should provide a *detailed* explanation of each command and its option, where "detailed" means more than the short explanation copied from the parser. In particular, how values of CLI options should be obtained? How to obtain the genesis utxo? How to obtain a signature? How to obtain asset currency symbol for the reserve tokens? Etc. This should be written in such a way that a person unfamiliar with the system knows how to obtain the required values and how to set up and use …

Updating the off-chain documentation

---

offchain/src/Main.purs
offchain/src/TrustlessSidechain/Effects/Env.purs
offchain/src/TrustlessSidechain/Effects/Errors/Parser.purs
offchain/src/TrustlessSidechain/InitSidechain/Checkpoint.purs
offchain/src/TrustlessSidechain/InitSidechain/FUEL.purs
offchain/src/TrustlessSidechain/InitSidechain/TokensMint.purs
offchain/src/TrustlessSidechain/NativeTokenManagement/IlliquidCirculationSupply.purs
offchain/src/TrustlessSidechain/NativeTokenManagement/Reserve.purs
offchain/src/TrustlessSidechain/NativeTokenManagement/Types.purs
offchain/src/TrustlessSidechain/Options/Specs.purs
offchain/src/TrustlessSidechain/Utils/Asset.purs
offchain/src/TrustlessSidechain/Utils/Utxos.purs
offchain/src/TrustlessSidechain/Versioning/V1.purs
offchain/test/Test/IlliquidCirculationSupply.purs
offchain/test/Test/Reserve.purs

Fixes #58, which was a leftover from Marcin's work in June. I also cleaned up imports to bring them up in line with our current code standards.

Clean up off chain code for the native token management

---

.github/workflows/ci.yml
flake.nix

fix(ci): remove unnecessary nix caches

---

flake.lock
flake.nix
nix/outputs.nix

chore: remove unused OCI image

---

.github/workflows/artifact.yml

https://github.com/input-output-hk/partner-chains-smart-contracts/actions/runs/10522978431

feat: artifact.yml can optionally draft a release page and automatically attach assets

---

.github/workflows/ci.yml
CHANGELOG.md
flake.nix
nix/offchain.nix
nix/outputs.nix
nix/packages/default.nix
nix/shell.nix
offchain/README.md
offchain/package-lock.json
offchain/package.json
offchain/spago.dhall
offchain/src/TrustlessSidechain/Options/Specs.purs
onchain/app/gen-signatures/GenOutput.hs
onchain/app/gen-signatures/Main.hs

chore: update naming to pc-contracts-cli

---

offchain/src/TrustlessSidechain/Utils/Crypto.js
offchain/src/TrustlessSidechain/Utils/Crypto.purs

Cleanup Utils.Crypto

---

nix/outputs.nix
release.sh

Release script

---

release.sh

Release script improvements

---

.github/workflows/ci.yml

Use `nix-build` in the github workflow for more helpful output during builds.

Use nix-build

---

CHANGELOG.md
offchain/package.json
onchain/trustless-sidechain.cabal

chore: bump version to v6.2.0

---

CHANGELOG.md
offchain/package-lock.json
offchain/spago.dhall
offchain/src/Main.purs

Print error messages on stderr

---

.github/workflows/release.yml

- Cleanup some repeated steps
- Make specifying a new tag optional

feat(release): use package.json version as default

---

CHANGELOG.md
offchain/src/TrustlessSidechain/Effects/Errors/Parser.purs

Improve some error messages

---

CHANGELOG.md
offchain/src/TrustlessSidechain/InitSidechain/Init.purs
offchain/test/Test/Reserve.purs

Remove the usage of InitTokens from NativeTokenManagement

---

CHANGELOG.md
offchain/package.json
onchain/trustless-sidechain.cabal
raw-scripts/Cargo.toml

chore: bump version to v6.2.2

---

offchain/package-lock.json
release.sh

Fix: make release.sh update package-lock.json

---

CHANGELOG.md
offchain/package-lock.json
offchain/package.json
onchain/trustless-sidechain.cabal
raw-scripts/Cargo.toml

chore: bump version to v7.0.0

---

nix/checks.nix

add whitespace fixing pre-commit hooks

---

.changes/7.0.0.md
.changes/header.tpl.md
.changie.yaml
.github/pull_request_template.md
CONTRIBUTING.md
nix/shells.nix
release.sh

add changie

---

offchain/packages.dhall

fix PureScript package-set in offchain

---

Makefile

fix: use requires_nix_shell for npx instead

---

.changes/7.0.1.md
.changes/unreleased/Removed-20241112-165602.yaml
CHANGELOG.md
offchain/package-lock.json
offchain/package.json
onchain/trustless-sidechain.cabal
raw-scripts/Cargo.toml

chore: bump version to v7.0.1

---

.changes/unreleased/Added-20241122-095521.yaml
.changes/unreleased/Changed-20241122-095528.yaml
.changes/unreleased/Changed-20241122-095537.yaml
CHANGELOG.md
offchain/README.md
offchain/package-lock.json
offchain/package.json
offchain/packages.dhall
offchain/spago-packages.nix
offchain/src/Main.purs
offchain/src/TrustlessSidechain/NativeTokenManagement/Reserve.purs
offchain/src/TrustlessSidechain/Options/Specs.purs
offchain/src/TrustlessSidechain/Utils/Transaction.purs
offchain/test/Test/DParameter.purs
offchain/test/Test/IlliquidCirculationSupply.purs
offchain/test/Test/PermissionedCandidates.purs
offchain/test/Test/Reserve.purs

add reserve-update-settings

---

.github/workflows/release.yml
offchain/Makefile

- Fix: set +x on pc-contracts-cli
- Call make instead of nix-build in release.yaml
- Remove npm publishing

Adjust release Github Action to changed build scripts

---

.changes/unreleased/Added-20250109-191639.yaml
flake.nix
onchain/app/serialise/Main.hs
onchain/src/TrustlessSidechain/ScriptId.hs
raw-scripts/src/lib.rs

Add missing script ids to raw-scripts crate

---

.changes/7.0.2.md
.changes/unreleased/Added-20241122-095521.yaml
.changes/unreleased/Added-20250109-144213.yaml
.changes/unreleased/Added-20250109-191639.yaml
.changes/unreleased/Changed-20241122-095528.yaml
.changes/unreleased/Changed-20241122-095537.yaml
.changes/unreleased/Changed-20250109-144241.yaml
.changes/unreleased/Fixed-20241120-123733.yaml
.changes/unreleased/Removed-20241119-105221.yaml
CHANGELOG.md
offchain/package-lock.json
offchain/package.json
onchain/trustless-sidechain.cabal
raw-scripts/Cargo.toml

chore: bump version to v7.0.2

---

.github/workflows/ci.yml
onchain/Makefile
release.sh

* It makes little sense to me to run one `update-scripts` make target without the other.
* Add raw-scripts-traced to release script and ci.

merge update-scripts targets

---

onchain/src/TrustlessSidechain/GovernedMap.hs
onchain/test/script-spec/GovernedMap.hs
onchain/test/script-spec/Main.hs
onchain/test/script-spec/ScriptSpecUtils.hs
onchain/trustless-sidechain.cabal

unit tests for governed map
